# Generated by Django 6.0.4 on 2026-05-09 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Укажите почту", max_length=254, unique=True, verbose_name="Почта"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, help_text="Введите ваше имя", max_length=30, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Введите вашу фамилию", max_length=30, verbose_name="Фамилия"
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.CharField(blank=True, help_text="Укажите страну", max_length=100, verbose_name="Страна"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Введите номер телефона", max_length=35, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Расскажите немного о себе", verbose_name="Информация о пользователе"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите аватар",
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет, может ли пользователь входить в систему. False до подтверждения email.",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, help_text="Дата и время последней активности пользователя"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to."
                        "A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
