# Generated by Django 6.0.4 on 2026-05-10 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        help_text="Краткое описание действия, которое вы будете выполнять",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Место, где выполняется действие (например: 'в офисе', 'дома')",
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Время, когда необходимо выполнять действие",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если это привычка - вознаграждение."
                        "Не может иметь вознаграждение или связанную привычку",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Опишите вознаграждение за выполнение полезной привычки"
                        "(нельзя использовать вместе со связанной привычкой)",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "frequency_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Как часто повторять привычку (в днях). Не чаще 1 раза в 7 дней.",
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Предполагаемое время на выполнение привычки в секундах (максимум 120 секунд)",
                        verbose_name="Время на выполнение (сек)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать привычку в общий доступ для других пользователей",
                        verbose_name="Публичная привычка",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите приятную привычку,"
                        "которая будет наградой за выполнение этой (только для полезных привычек)",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="habits.habit",
                        verbose_name="Связанная приятная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь создавший привычку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
