# Generated by Django 6.0.4 on 2026-05-10 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, обладающий правами на управление этой привычкой",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это привычка - вознаграждение."
                "Не может иметь вознаграждение или связанную привычку",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите приятную привычку,"
                "которая будет наградой за выполнение этой (только для полезных привычек)",
                limit_choices_to={"is_pleasant": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_to",
                to="habits.habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Опишите вознаграждение за выполнение полезной привычки"
                "(нельзя использовать вместе со связанной привычкой)",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь создавший привычку",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
