# Generated by Django 6.0.4 on 2026-05-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_owner_alter_habit_is_pleasant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это привычка - вознаграждение."
                "Не может иметь вознаграждение или связанную привычку",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите приятную привычку, которая будет наградой за выполнение этой"
                "(только для полезных привычек)",
                limit_choices_to={"is_pleasant": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_to",
                to="habits.habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Опишите вознаграждение за выполнение полезной привычки"
                "(нельзя использовать вместе со связанной привычкой)",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
