# Generated by Django 6.0.4 on 2026-05-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_is_pleasant_alter_habit_linked_habit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat-id",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это привычка - вознаграждение."
                "Не может иметь вознаграждение или связанную привычку",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите приятную привычку, которая будет наградой за выполнение этой"
                "(только для полезных привычек)",
                limit_choices_to={"is_pleasant": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_to",
                to="habits.habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Опишите вознаграждение за выполнение полезной привычки"
                "(нельзя использовать вместе со связанной привычкой)",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
